name: ogs-environment
channels:
  - conda-forge
dependencies:
  - python=3.12
  - ogs
  - ogstools
  - seaborn
  - jupytext
  - nbgitpuller
  - ipywidgets
  - gmsh
  - black
  - isort
  - pip
  - pip:
    - jupyterlab-code-formatter
